# binds
bind = $mainMod,        Y,      exec,             pkill waybar || waybar
## toggle gaps
bind = $mainMod,        G, exec, hyprctl keyword general:gaps_in 0 && hyprctl keyword general:gaps_out 0  && hyprctl keyword general:border_size 0
bind = $mainMod SHIFT,  G, exec, hyprctl keyword general:gaps_in 7 && hyprctl keyword general:gaps_out 10 && hyprctl keyword general:border_size 2

# decorations
general {
  col.active_border = rgba(d79921ee)
  col.inactive_border = rgba(595959aa)
  border_size = 3
}
