# binds
bind = $mainMod,        Y,      exec,             pkill waybar || waybar

# decorations
general {
  col.active_border = rgba(d79921ee)
  col.inactive_border = rgba(595959aa)
  border_size = 3
}
