background {
    monitor =
    color = rgba(18, 18, 18, 1.0)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(9ca8b0)
    inner_color = rgb(1e1e1e)
    font_color = rgb(e6e6e6)
    fade_on_empty = true
    placeholder_text = <i>password...</i>
    check_color = rgb(b0ada0)
    fail_color = rgb(b0a0a5)
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(230, 230, 230, 1.0)
    font_size = 64
    font_family = Rubik
    position = 0, 200
    halign = center
    valign = center
}
