# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Tell DBus and Portals that we are running on Hyprland/Wayland
exec-once = dbus-update-activation-environment --all
exec-once = killall xdg-desktop-portal xdg-desktop-portal-hyprland; /usr/libexec/xdg-desktop-portal-hyprland & sleep 2; /usr/libexec/xdg-desktop-portal &
# Manually start the portals in the correct order
exec-once = killall xdg-desktop-portal xdg-desktop-portal-hyprland; /usr/libexec/xdg-desktop-portal-hyprland & sleep 2; /usr/libexec/xdg-desktop-portal &

exec-once = pipewire & hypridle & swww-daemon & waybar

exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = wl-clip-persist --clipboard regular
