###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
#$terminal = kitty
#$fileManager = kitty -e yazi
$terminal = foot
$fileManager = foot -e yazi
$menu = rofi-custom
# $menu = wofi --show drun
#$web = firefox
$web = flatpak run com.brave.Browser
