# binds
bind = $mainMod,        Y,      exec,             pkill waybar || waybar

# decorations
# general {
#     border_size = 3
#     col.active_border = rgba(9ca8b0ff)
#     col.inactive_border = rgba(333333ff)
# }
